//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Wiseape.UtilityApp.CodeGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEXTBOX")]
        public string TEXTBOX {
            get {
                return ((string)(this["TEXTBOX"]));
            }
            set {
                this["TEXTBOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEXTAREA")]
        public string TEXTAREA {
            get {
                return ((string)(this["TEXTAREA"]));
            }
            set {
                this["TEXTAREA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECTBOX")]
        public string SELECTBOX {
            get {
                return ((string)(this["SELECTBOX"]));
            }
            set {
                this["SELECTBOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RADIOGROUP")]
        public string RADIOGROUP {
            get {
                return ((string)(this["RADIOGROUP"]));
            }
            set {
                this["RADIOGROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DATETIME")]
        public string DATETIME {
            get {
                return ((string)(this["DATETIME"]));
            }
            set {
                this["DATETIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TABPAGES")]
        public string TABPAGES {
            get {
                return ((string)(this["TABPAGES"]));
            }
            set {
                this["TABPAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GRID")]
        public string GRID {
            get {
                return ((string)(this["GRID"]));
            }
            set {
                this["GRID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHECKBOXGROUP")]
        public string CHECKBOXGROUP {
            get {
                return ((string)(this["CHECKBOXGROUP"]));
            }
            set {
                this["CHECKBOXGROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FILEUPLOAD")]
        public string FILEUPLOAD {
            get {
                return ((string)(this["FILEUPLOAD"]));
            }
            set {
                this["FILEUPLOAD"] = value;
            }
        }
    }
}
